; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "LicencesBoualem"
#define MyAppVersion "1.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "GestionnaireLicences.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{19F1BA2D-2A5A-4FDF-853B-57D134B996FE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\uninstall.ico
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Bureau\Projet_final_Deploiement
OutputBaseFilename=setupLicencesBoualem
SetupIconFile=C:\Bureau\Projet_final_Deploiement\icons\License-manager.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Bureau\Projet_final_Deploiement\GestionnaireLicences\GestionnaireLicences\GestionnaireLicences\bin\Release\net6.0-windows7.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Bureau\Projet_final_Deploiement\GestionnaireLicences\GestionnaireLicences\GestionnaireLicences\bin\Release\net6.0-windows7.0\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "C:\Bureau\Projet_final_Deploiement\icons\License-manager.ico"; DestDir: "{app}"
Source: "C:\Bureau\Projet_final_Deploiement\icons\uninstall.ico"; DestDir: "{app}"

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\License-manager.ico"
Name: "{group}\Désinstaller {#MyAppName}"; Filename: "{uninstallexe}"; IconFilename: "{app}\uninstall.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\License-manager.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  InfoPage: TWizardPage;

procedure InitializeWizard;
var
  LabelInfo: TNewStaticText;
begin
  { Création d'une page personnalisée avant l'installation }
  InfoPage := CreateCustomPage(
    wpWelcome,
    'Information importante',
    'Veuillez lire ce message avant de continuer l''installation'
  );
  
  { Ajout du texte en dur }
  LabelInfo := TNewStaticText.Create(InfoPage);
  LabelInfo.Parent := InfoPage.Surface;
  LabelInfo.Caption :=
    'Ce logiciel a été développé par Steven Duquette' + #13#10 +
    'et c''est une application proche de la perfection.';
  LabelInfo.Left := 0;
  LabelInfo.Top := 0;
  LabelInfo.Width := InfoPage.SurfaceWidth;
end;

function InitializeSetup(): Boolean;
var
  InstallPath: String;
  FreeSpace, TotalSpace: Cardinal;
  FreeMB: Cardinal;
begin
  { Vérification d'au moins 1GB d'espace libre }
  InstallPath := ExpandConstant('{autopf}');
  if GetSpaceOnDisk(InstallPath, False, FreeSpace, TotalSpace) then
  begin
    FreeMB := FreeSpace div (1024*1024);
    if FreeMB < 1024 then
    begin
      MsgBox('Erreur : Il faut au moins 1 GB d''espace disque libre pour installer cette application.',
             mbError, MB_OK);
      Result := False;  { Annule l'installation }
    end
    else
      Result := True;
  end
  else
  begin
    { Si on ne peut pas vérifier l'espace, on continue quand même }
    Result := True;
  end;
end;